codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        target: 40%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 30%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

flags:
  unittests:
    paths:
      - sendgrid/
    carryforward: false
  acceptancetests:
    paths:
      - sendgrid/
    carryforward: false

ignore:
  - "examples/"
  - "tools/"
  - "scripts/"
  - "docs/"
  - "templates/"
  - "**/*_test.go"
  - "main.go"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true
  require_base: true
  require_head: true

github_checks:
  annotations: true
