name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature has not been requested before
          required: true
        - label: I have checked the [documentation](https://github.com/arslanbekov/terraform-provider-sendgrid/blob/master/docs/RESOURCES.md) to confirm this feature doesn't already exist
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Resource
        - New Data Source
        - Enhancement to Existing Resource
        - Provider Configuration
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're experiencing
      placeholder: |
        I'm trying to accomplish... but I can't because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: |
        I would like to be able to...
        This could be implemented by...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a DevOps engineer, I want to...
        2. This would help when...
        3. Teams could benefit by...
    validations:
      required: true

  - type: textarea
    id: example-config
    attributes:
      label: Example Configuration
      description: Provide an example of how you'd like to use this feature
      placeholder: |
        resource "sendgrid_new_feature" "example" {
          name        = "example"
          description = "Example configuration"
        }
      render: hcl
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: |
        I've tried... but it doesn't work because...
        Another approach could be... but...
    validations:
      required: false

  - type: textarea
    id: sendgrid-api
    attributes:
      label: SendGrid API Reference
      description: If applicable, provide links to relevant SendGrid API documentation
      placeholder: |
        https://www.twilio.com/docs/sendgrid/api-reference/...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Important for my workflow
        - Medium - Nice to have
        - Low - Enhancement/Quality of life
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related issues, similar features in other providers, or documentation
      placeholder: |
        - Similar feature in AWS provider: https://...
        - Related Issue #123
    validations:
      required: false
